// This file is normally generated by FlutterFire CLI (`flutterfire configure`).
//
// Since this repo didn't have Firebase configured yet, we provide a placeholder
// to keep the app compiling (especially on web).
//
// IMPORTANT:
// - Replace this file by running `flutterfire configure` (recommended), or
// - Fill the options below with your Firebase project values.
//
// If you keep the placeholder values, Firebase initialization will fail and
// the app will show "Firebase not ready" in chat screens.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return web;
    }
  }

  // TODO: Replace with real options (or run flutterfire configure).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
    authDomain: 'CHANGE_ME',
    storageBucket: 'CHANGE_ME',
    measurementId: 'CHANGE_ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
    iosBundleId: 'CHANGE_ME',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
    iosBundleId: 'CHANGE_ME',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
  );
}

